language: go

go:
  - 1.8.x

install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

script:
  - go test ./...
  - mkdir -p build
  - for os in linux darwin windows; do go build GOOS=$os GOARCH=amd64 go build -o build/yaml2p.$GOOS.$GOARCH; done
